language: csharp
mono: none
dist: bionic
dotnet: 2.2.103
solution: Xyaneon.Games.Cards.sln
script:
  - dotnet build -c Release
  - dotnet test -c Release
  - dotnet pack -c Release --no-build --include-symbols
deploy:
  skip_cleanup: true
  provider: script
  script: dotnet nuget push Xyaneon.Games.Cards/bin/Release/Xyaneon.Games.Cards.*.nupkg --api-key $NUGET_API_KEY --source https://api.nuget.org/v3/index.json
  on:
    tags: true
    condition: $TRAVIS_TAG =~ ^v[0-9]+\.[0-9]+\.[0-9]+$
