name: Pull request

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
      
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
      
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Test
      run: dotnet test --no-build --verbosity normal --collect:"XPlat Code Coverage" --settings ./Xyaneon.Games.Cards.Test/coverlet.runsettings
    
    # Workaround for issue: https://github.com/microsoft/vstest/issues/2378
    - name: Relocate test coverage results
      run: mv ./Xyaneon.Games.Cards.Test/TestResults/**/coverage.info ./Xyaneon.Games.Cards.Test/TestResults/
    
    - name: Upload coverage file to Coveralls.io
      uses: coverallsapp/github-action@v2.3.6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        file: ./Xyaneon.Games.Cards.Test/TestResults/coverage.info
        format: lcov
