name: Release

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        
    - name: Restore .NET dependencies
      run: dotnet restore
      
    - name: Install Node dependencies
      run: npm ci
      
    - name: Build
      run: dotnet build -c Release --no-restore
      
    - name: Test
      run: dotnet test -c Release --no-build --verbosity normal
    
    - name: Semantic Release
      env:
        GH_TOKEN: ${{ secrets.SEMANTIC_RELEASE }}
        NUGET_TOKEN: ${{ secrets.NUGET_TOKEN }}
      run: npx semantic-release
